export const PERMISSIONS = {
  CA: {
    GET: 'CA::GET',
    SPACES: {
      CREATE: 'CA:SPACES:CREATE',
      UPDATE: 'CA:SPACES:UPDATE',
      DELETE: 'CA:SPACES:DELETE',
      CERTS: {
        CREATE: (spaceId: string) => `CA:SPACES:${spaceId}:CERTS:CREATE`,
        READ: (spaceId: string) => `CA:SPACES:${spaceId}:CERTS:READ`,
        UPDATE: (spaceId: string) => `CA:SPACES:${spaceId}:CERTS:UPDATE`,
        DELETE: (spaceId: string) => `CA:SPACES:${spaceId}:CERTS:DELETE`
      }
    },
    AUTHORITIES: {
      CREATE: 'CA:AUTHORITIES:CREATE',
      UPDATE: 'CA:AUTHORITIES:UPDATE',
      DELETE: 'CA:AUTHORITIES:DELETE',
      CERTS: {
        CREATE: (caId: string) => `CA:AUTHORITIES:${caId}:CERTS:CREATE`,
        READ: (caId: string) => `CA:AUTHORITIES:${caId}:CERTS:READ`,
        UPDATE: (caId: string) => `CA:AUTHORITIES:${caId}:CERTS:UPDATE`,
        DELETE: (caId: string) => `CA:AUTHORITIES:${caId}:CERTS:DELETE`
      }
    }
  },
  JOBS: {
    GET: 'JOBS::GET',
    JOB: {
      CREATE: 'JOBS:JOB::CREATE',
      CREATE_SPECIFIC: (definitionId: string) =>
        `JOBS:JOB:${definitionId}:CREATE`
    },
    DEFINITION: {
      CREATE: 'JOBS:DEFINITION::CREATE',
      UPDATE: 'JOBS:DEFINITION::UPDATE',
      DELETE: 'JOBS:DEFINITION::DELETE'
    }
  },
  HIERA: {
    GET: 'HIERA::GET',
    KEY_MODELS_DYNAMIC: {
      CREATE: 'HIERA:KEY_MODELS_DYNAMIC::CREATE',
      DELETE: 'HIERA:KEY_MODELS_DYNAMIC::DELETE'
    },
    KEYS: {
      CREATE: 'HIERA:KEYS::CREATE',
      UPDATE: 'HIERA:KEYS::UPDATE',
      DELETE: 'HIERA:KEYS::DELETE'
    },
    LEVELS: {
      CREATE: 'HIERA:LEVELS::CREATE',
      UPDATE: 'HIERA:LEVELS::UPDATE',
      DELETE: 'HIERA:LEVELS::DELETE'
    },
    LEVEL_DATA: {
      CREATE: 'HIERA:LEVEL_DATA::CREATE',
      UPDATE: 'HIERA:LEVEL_DATA::UPDATE',
      DELETE: 'HIERA:LEVEL_DATA::DELETE',
      CREATE_SPECIFIC: (keyId: string) => `HIERA:LEVEL_DATA:${keyId}:CREATE`,
      READ_SPECIFIC: (keyId: string) => `HIERA:LEVEL_DATA:${keyId}:READ`,
      UPDATE_SPECIFIC: (keyId: string) => `HIERA:LEVEL_DATA:${keyId}:UPDATE`,
      DELETE_SPECIFIC: (keyId: string) => `HIERA:LEVEL_DATA:${keyId}:DELETE`
    }
  },
  NODES: {
    CREATE: 'NODES::CREATE',
    UPDATE: 'NODES::UPDATE',
    DELETE: 'NODES::DELETE',
    CATALOG_CACHE: {
      DELETE: 'NODES:CATALOG_CACHE::DELETE'
    },
    GROUPS: {
      GET: 'NODES:GROUPS::GET',
      CREATE: 'NODES:GROUPS::CREATE',
      UPDATE: 'NODES:GROUPS::UPDATE',
      DELETE: 'NODES:GROUPS::DELETE'
    },
    SECRETS_REDACTOR: {
      CREATE: 'NODES:SECRETS_REDACTOR::CREATE',
      DELETE: 'NODES:SECRETS_REDACTOR::DELETE'
    }
  },
  PYPPETDB: {
    NODES: {
      GET: 'PYPPETDB:NODES::GET',
      DELETE: 'PYPPETDB:NODES::DELETE'
    }
  },
  TEAMS: {
    GET: 'TEAMS::GET',
    CREATE: 'TEAMS::CREATE',
    UPDATE: 'TEAMS::UPDATE',
    DELETE: 'TEAMS::DELETE'
  },
  USERS: {
    GET: 'USERS::GET',
    CREATE: 'USERS::CREATE',
    UPDATE: 'USERS::UPDATE',
    DELETE: 'USERS::DELETE',
    CREDENTIALS: {
      GET: 'USERS:CREDENTIALS::GET',
      CREATE: 'USERS:CREDENTIALS::CREATE',
      UPDATE: 'USERS:CREDENTIALS::UPDATE',
      DELETE: 'USERS:CREDENTIALS::DELETE'
    }
  }
} as const

export const ALL_PERMISSIONS: string[] = [
  PERMISSIONS.CA.GET,
  PERMISSIONS.CA.SPACES.CREATE,
  PERMISSIONS.CA.SPACES.UPDATE,
  PERMISSIONS.CA.SPACES.DELETE,
  PERMISSIONS.CA.AUTHORITIES.CREATE,
  PERMISSIONS.CA.AUTHORITIES.UPDATE,
  PERMISSIONS.CA.AUTHORITIES.DELETE,

  PERMISSIONS.JOBS.GET,
  PERMISSIONS.JOBS.JOB.CREATE,
  PERMISSIONS.JOBS.DEFINITION.CREATE,
  PERMISSIONS.JOBS.DEFINITION.UPDATE,
  PERMISSIONS.JOBS.DEFINITION.DELETE,

  PERMISSIONS.HIERA.GET,
  PERMISSIONS.HIERA.KEY_MODELS_DYNAMIC.CREATE,
  PERMISSIONS.HIERA.KEY_MODELS_DYNAMIC.DELETE,
  PERMISSIONS.HIERA.KEYS.CREATE,
  PERMISSIONS.HIERA.KEYS.UPDATE,
  PERMISSIONS.HIERA.KEYS.DELETE,
  PERMISSIONS.HIERA.LEVELS.CREATE,
  PERMISSIONS.HIERA.LEVELS.UPDATE,
  PERMISSIONS.HIERA.LEVELS.DELETE,
  PERMISSIONS.HIERA.LEVEL_DATA.CREATE,
  PERMISSIONS.HIERA.LEVEL_DATA.UPDATE,
  PERMISSIONS.HIERA.LEVEL_DATA.DELETE,

  PERMISSIONS.NODES.CREATE,
  PERMISSIONS.NODES.UPDATE,
  PERMISSIONS.NODES.DELETE,
  PERMISSIONS.NODES.CATALOG_CACHE.DELETE,
  PERMISSIONS.NODES.GROUPS.GET,
  PERMISSIONS.NODES.GROUPS.CREATE,
  PERMISSIONS.NODES.GROUPS.UPDATE,
  PERMISSIONS.NODES.GROUPS.DELETE,
  PERMISSIONS.NODES.SECRETS_REDACTOR.CREATE,
  PERMISSIONS.NODES.SECRETS_REDACTOR.DELETE,

  PERMISSIONS.PYPPETDB.NODES.GET,
  PERMISSIONS.PYPPETDB.NODES.DELETE,

  PERMISSIONS.TEAMS.GET,
  PERMISSIONS.TEAMS.CREATE,
  PERMISSIONS.TEAMS.UPDATE,
  PERMISSIONS.TEAMS.DELETE,

  PERMISSIONS.USERS.GET,
  PERMISSIONS.USERS.CREATE,
  PERMISSIONS.USERS.UPDATE,
  PERMISSIONS.USERS.DELETE,
  PERMISSIONS.USERS.CREDENTIALS.GET,
  PERMISSIONS.USERS.CREDENTIALS.CREATE,
  PERMISSIONS.USERS.CREDENTIALS.UPDATE,
  PERMISSIONS.USERS.CREDENTIALS.DELETE
]
