<template>
  <ComponentDialogWarning
    :msg="dialogDeleteMsg"
    :show="dialogDeleteShow"
    @response="(action) => dialogDeleteEvent(action)"
  />
  <v-card>
    <v-form ref="form" v-model="formDataValid">
      <v-card-text>
        <v-switch
          v-model="formDataReadOnly"
          v-if="formButtonEditShow"
          :true-value="false"
          :false-value="true"
          label="Modify"
        ></v-switch>
        <v-text-field
          v-model="formData.level_id"
          :readonly="formInputLevelIdReadOnly"
          :rules="[() => !!formData.level_id || 'This field is required']"
          append-inner-icon="mdi-layers"
          label="Level ID"
        ></v-text-field>
        <v-text-field
          v-model="formData.id"
          :readonly="formInputDataIdReadOnly"
          :rules="[() => !!formData.id || 'This field is required']"
          append-inner-icon="mdi-identifier"
          label="Data ID"
        ></v-text-field>
        <v-text-field
          v-model="formData.key_id"
          :readonly="formInputKeyIdReadOnly"
          :rules="[() => !!formData.key_id || 'This field is required']"
          append-inner-icon="mdi-key"
          label="Key ID"
        ></v-text-field>
        <v-text-field
          v-model.number="formData.priority"
          :readonly="formInputPriorityReadOnly"
          :rules="[() => formData.priority !== null && formData.priority !== undefined && formData.priority !== '' || 'This field is required']"
          type="number"
          append-inner-icon="mdi-numeric"
          label="Priority"
        ></v-text-field>
        <template v-if="formInputFactsReadOnly">
          <v-textarea
            v-model="formData.factsJson"
            :readonly="formInputFactsReadOnly"
            :rules="[validateJsonObject]"
            append-inner-icon="mdi-code-json"
            label="Facts (JSON Object)"
            rows="5"
          ></v-textarea>
        </template>
        <template v-else>
          <v-text-field
            v-for="field in factFields"
            :key="field"
            v-model="factValues[field]"
            :label="`Fact: ${field}`"
            :rules="[() => !!factValues[field] || 'This field is required']"
            append-inner-icon="mdi-tag"
          ></v-text-field>
        </template>
        <v-textarea
          v-model="formData.dataJson"
          :readonly="formDataReadOnly"
          :rules="[validateJson]"
          append-inner-icon="mdi-code-json"
          label="Data (JSON)"
          rows="8"
        ></v-textarea>
      </v-card-text>
      <v-divider v-if="!formDataReadOnly"></v-divider>
      <v-card-actions v-if="!formDataReadOnly">
        <v-btn variant="text" @click="formReset">Reset</v-btn>
        <v-spacer></v-spacer>
        <v-btn
          v-if="formButtonDeleteShow"
          color="red"
          variant="text"
          @click="formDelete"
          >Delete
        </v-btn>
        <v-btn color="primary" variant="text" @click="formSubmit">Submit</v-btn>
      </v-card-actions>
    </v-form>
  </v-card>
</template>

<script setup>
import { reactive, ref, nextTick, watch, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router/dist/vue-router'

import ComponentDialogWarning from '@/components/ComponentDialogWarning.vue'

import api from '@/api/common'
import { apiErrorStore } from '@/store/api_error'

const apiError = apiErrorStore()

const route = useRoute()
const router = useRouter()

const dialogDeleteShow = ref(false)
const dialogDeleteMsg = ref('')

function dialogDeleteEvent(action) {
  if (action === 'cancel') {
    dialogDeleteShow.value = false
    dialogDeleteMsg.value = ''
  } else {
    dialogDeleteShow.value = false
    dialogDeleteMsg.value = ''
    let url = `/api/v1/hiera/data/${formData.level_id}/${formData.id}/${formData.key_id}`
    api.delete(url).then(() => {
      router.push({
        name: 'HieraLevelDataSearch'
      })
    })
  }
}

const form = ref(null)
const formData = reactive({})
const formDataReadOnly = ref(true)
const formDataValid = ref(false)
const formButtonDeleteShow = ref(true)
const formButtonEditShow = ref(false)
const formInputLevelIdReadOnly = ref(true)
const formInputDataIdReadOnly = ref(true)
const formInputKeyIdReadOnly = ref(true)
const formInputPriorityReadOnly = ref(true)
const formInputFactsReadOnly = ref(true)

// Extract placeholders from level_id and create fact fields
const factFields = computed(() => {
  if (!formData.level_id) return []
  const regex = /\{([^}]+)\}/g
  const fields = []
  let match
  while ((match = regex.exec(formData.level_id)) !== null) {
    fields.push(match[1])
  }
  return fields
})

// Individual fact values
const factValues = reactive({})

// Auto-generate data_id based on level_id and fact values
const autoGeneratedDataId = computed(() => {
  if (!formData.level_id) return ''
  let dataId = formData.level_id
  factFields.value.forEach(field => {
    const value = factValues[field] || ''
    dataId = dataId.replace(`{${field}}`, value)
  })
  return dataId
})

// Watch for auto-generated data_id changes
watch(autoGeneratedDataId, (newValue) => {
  const isNewLevel = route.params.level_id === '_new'
  const isNewData = route.params.data_id === '_new'
  const isNewKey = route.params.key_id === '_new'
  const isNew = isNewLevel && isNewData && isNewKey

  if (isNew) {
    formData.id = newValue
  }
})

// Watch for level_id changes to reset fact values
watch(() => formData.level_id, () => {
  const isNewLevel = route.params.level_id === '_new'
  const isNewData = route.params.data_id === '_new'
  const isNewKey = route.params.key_id === '_new'
  const isNew = isNewLevel && isNewData && isNewKey

  if (isNew) {
    // Clear existing fact values
    Object.keys(factValues).forEach(key => delete factValues[key])
    // Initialize new fact fields
    factFields.value.forEach(field => {
      factValues[field] = ''
    })
  }
})

function validateJson(value) {
  if (!value) {
    return 'This field is required'
  }
  try {
    JSON.parse(value)
    return true
  } catch (e) {
    return 'Invalid JSON format'
  }
}

function validateJsonObject(value) {
  if (!value) {
    return 'This field is required'
  }
  try {
    const parsed = JSON.parse(value)
    if (typeof parsed !== 'object' || Array.isArray(parsed)) {
      return 'Must be a valid JSON object (not an array)'
    }
    return true
  } catch (e) {
    return 'Invalid JSON format'
  }
}

function initializeFormState() {
  const isNewLevel = route.params.level_id === '_new'
  const isNewData = route.params.data_id === '_new'
  const isNewKey = route.params.key_id === '_new'
  const isNew = isNewLevel && isNewData && isNewKey

  if (isNew) {
    formInputLevelIdReadOnly.value = false
    formInputDataIdReadOnly.value = false
    formInputKeyIdReadOnly.value = false
    formInputPriorityReadOnly.value = false
    formInputFactsReadOnly.value = false
    formDataReadOnly.value = false
    formButtonDeleteShow.value = false
    formButtonEditShow.value = false
  } else {
    formInputLevelIdReadOnly.value = true
    formInputDataIdReadOnly.value = true
    formInputKeyIdReadOnly.value = true
    formInputPriorityReadOnly.value = true
    formInputFactsReadOnly.value = true
    formDataReadOnly.value = true
    formButtonEditShow.value = true
  }
  formGetData()
}

// Initialize on mount
initializeFormState()

// Watch for route parameter changes
watch(() => [route.params.level_id, route.params.data_id, route.params.key_id], () => {
  initializeFormState()
})

function formDelete() {
  dialogDeleteShow.value = true
  dialogDeleteMsg.value = `Are you sure you want to delete Hiera Level Data: ${route.params.level_id}/${route.params.data_id}/${route.params.key_id}`
}

function formReset(event) {
  event.preventDefault()
  formGetData()
  formDataValid.value = false
  nextTick(() => {
    form.value.resetValidation()
  })
}

function formSubmit(event) {
  event.preventDefault()

  const isNewLevel = route.params.level_id === '_new'
  const isNewData = route.params.data_id === '_new'
  const isNewKey = route.params.key_id === '_new'
  const isNew = isNewLevel && isNewData && isNewKey

  let facts, data
  try {
    if (isNew) {
      // Build facts from individual fact fields
      facts = {}
      factFields.value.forEach(field => {
        facts[field] = factValues[field]
      })
    } else {
      facts = JSON.parse(formData.factsJson)
    }
    data = JSON.parse(formData.dataJson)
  } catch (e) {
    return
  }

  let method = 'put'
  let url = `/api/v1/hiera/data/${formData.level_id}/${formData.id}/${formData.key_id}`
  let requestData = {}

  if (isNew) {
    method = 'post'
    requestData = {
      priority: formData.priority,
      facts: facts,
      data: data
    }
  } else {
    requestData = {
      data: data
    }
  }

  api.request(method, url, requestData).then(() => {
    if (isNew) {
      formButtonDeleteShow.value = true
      router.push({
        name: 'HieraLevelDataCRUD',
        params: {
          level_id: formData.level_id,
          data_id: formData.id,
          key_id: formData.key_id
        }
      })
    } else {
      formDataReadOnly.value = true
      formGetData()
    }
  })
}

function formGetData() {
  const isNewLevel = route.params.level_id === '_new'
  const isNewData = route.params.data_id === '_new'
  const isNewKey = route.params.key_id === '_new'
  const isNew = isNewLevel && isNewData && isNewKey

  if (isNew) {
    formDataValid.value = false
    nextTick(() => {
      form.value.resetValidation()
    })
    formData['level_id'] = ''
    formData['id'] = ''
    formData['key_id'] = ''
    formData['priority'] = null
    formData['factsJson'] = '{}'
    formData['dataJson'] = '{}'
    // Clear fact values
    Object.keys(factValues).forEach(key => delete factValues[key])
  } else {
    const url = `/api/v1/hiera/data/${route.params.level_id}/${route.params.data_id}/${route.params.key_id}`
    api.get(url).then((data) => {
      if (data) {
        formData['level_id'] = data['level_id']
        formData['id'] = data['id']
        formData['key_id'] = data['key_id']
        formData['priority'] = data['priority']
        formData['factsJson'] = JSON.stringify(data['facts'], null, 2)
        formData['dataJson'] = JSON.stringify(data['data'], null, 2)
      }
    })
  }
}
</script>
